#if !canImport(ObjectiveC)
import XCTest

extension ArithmeticTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArithmeticTest = [
        ("testColorOperation", testColorOperation),
        ("testFloat32ColorPixelOperation", testFloat32ColorPixelOperation),
        ("testFloat32ComponentsOperation", testFloat32ComponentsOperation),
        ("testFloat64ColorPixelOperation", testFloat64ColorPixelOperation),
        ("testFloat64ComponentsOperation", testFloat64ComponentsOperation),
        ("testTensorOperation", testTensorOperation),
    ]
}

extension BrotliTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BrotliTest = [
        ("testBrotli", testBrotli),
        ("testBrotliDecoderPerformance", testBrotliDecoderPerformance),
        ("testBrotliEncoderPerformance", testBrotliEncoderPerformance),
    ]
}

extension CollectionTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionTest = [
        ("testCollectionRangeOf", testCollectionRangeOf),
        ("testConcatCollection", testConcatCollection),
        ("testIndexedCollection", testIndexedCollection),
        ("testLazySequenceScan", testLazySequenceScan),
        ("testNextPermute1", testNextPermute1),
        ("testNextPermute2", testNextPermute2),
        ("testOptionOneCollection1", testOptionOneCollection1),
        ("testOptionOneCollection2", testOptionOneCollection2),
        ("testSequenceScan", testSequenceScan),
        ("testSequenceStorageEqual", testSequenceStorageEqual),
        ("testSequenceStorageEqual2", testSequenceStorageEqual2),
        ("testSequenceStorageEqual3", testSequenceStorageEqual3),
        ("testSequenceStorageEqual4", testSequenceStorageEqual4),
    ]
}

extension ColorSpaceTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorSpaceTest = [
        ("testLoadingColorSpace", testLoadingColorSpace),
    ]
}

extension FontTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FontTest = [
        ("testLoadingFont", testLoadingFont),
    ]
}

extension FourierTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FourierTest = [
        ("testCircularConvolve", testCircularConvolve),
        ("testCircularConvolveComplex", testCircularConvolveComplex),
        ("testCircularConvolvePerformance", testCircularConvolvePerformance),
        ("testCircularConvolvePerformanceX2", testCircularConvolvePerformanceX2),
        ("testCircularConvolvePerformanceX3", testCircularConvolvePerformanceX3),
        ("testConvolve", testConvolve),
        ("testConvolveComplex", testConvolveComplex),
        ("testDCTII", testDCTII),
        ("testDCTIII", testDCTIII),
        ("testDCTIV", testDCTIV),
        ("testDSTII", testDSTII),
        ("testDSTIII", testDSTIII),
        ("testDSTIV", testDSTIV),
        ("testFourierBPerformance", testFourierBPerformance),
        ("testFourierBPerformanceX2", testFourierBPerformanceX2),
        ("testFourierCPerformance", testFourierCPerformance),
        ("testFourierCPerformanceX2", testFourierCPerformanceX2),
        ("testFourierCPerformanceX3", testFourierCPerformanceX3),
        ("testInverseRadix2CooleyTukeyA", testInverseRadix2CooleyTukeyA),
        ("testInverseRadix2CooleyTukeyB", testInverseRadix2CooleyTukeyB),
        ("testInverseRadix2CooleyTukeyComplexA", testInverseRadix2CooleyTukeyComplexA),
        ("testInverseRadix2CooleyTukeyComplexB", testInverseRadix2CooleyTukeyComplexB),
        ("testNegacyclicConvolve", testNegacyclicConvolve),
        ("testNegacyclicConvolveComplex", testNegacyclicConvolveComplex),
        ("testRadix2CooleyTukeyA", testRadix2CooleyTukeyA),
        ("testRadix2CooleyTukeyB", testRadix2CooleyTukeyB),
        ("testRadix2CooleyTukeyComplexA", testRadix2CooleyTukeyComplexA),
        ("testRadix2CooleyTukeyComplexB", testRadix2CooleyTukeyComplexB),
    ]
}

extension ImageCodecTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageCodecTest = [
        ("testBmp1", testBmp1),
        ("testBmp2", testBmp2),
        ("testPng1", testPng1),
        ("testPng1Interlaced", testPng1Interlaced),
        ("testPng2", testPng2),
        ("testPng2Interlaced", testPng2Interlaced),
        ("testPng3", testPng3),
        ("testPng3Interlaced", testPng3Interlaced),
        ("testPng4", testPng4),
        ("testPng4Interlaced", testPng4Interlaced),
        ("testPngSuite", testPngSuite),
        ("testRGB555Big", testRGB555Big),
        ("testRGB555Little", testRGB555Little),
        ("testRGB8816Big", testRGB8816Big),
        ("testRGBA32Big", testRGBA32Big),
        ("testRGBA32Little", testRGBA32Little),
        ("testRGBA64Big", testRGBA64Big),
        ("testRGBA64Little", testRGBA64Little),
        ("testRGBFloat32Big", testRGBFloat32Big),
        ("testRGBFloat32Little", testRGBFloat32Little),
        ("testRGBFloat64Big", testRGBFloat64Big),
        ("testRGBFloat64Little", testRGBFloat64Little),
        ("testTiff1", testTiff1),
        ("testTiff1Deflate", testTiff1Deflate),
        ("testTiff2", testTiff2),
        ("testTiff2Deflate", testTiff2Deflate),
        ("testTiff3", testTiff3),
        ("testTiff3Deflate", testTiff3Deflate),
        ("testTiff4", testTiff4),
        ("testTiff4Deflate", testTiff4Deflate),
        ("testTiff5", testTiff5),
        ("testTiff5Deflate", testTiff5Deflate),
        ("testTiff6", testTiff6),
        ("testTiff6Deflate", testTiff6Deflate),
        ("testTiffOrientation1", testTiffOrientation1),
        ("testTiffOrientation2", testTiffOrientation2),
    ]
}

extension ImageTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageTest = [
        ("testClipPerformance", testClipPerformance),
        ("testColorSpaceConversionPerformance", testColorSpaceConversionPerformance),
        ("testDrawing", testDrawing),
        ("testImageGaussianBlur", testImageGaussianBlur),
        ("testLinearGradientPerformance", testLinearGradientPerformance),
        ("testMeshGradientPerformance", testMeshGradientPerformance),
        ("testOrthographicProjectPerformance", testOrthographicProjectPerformance),
        ("testPerspectiveProjectPerformance", testPerspectiveProjectPerformance),
        ("testRadialGradientPerformance", testRadialGradientPerformance),
        ("testResamplingCosineAntialiasPerformance", testResamplingCosineAntialiasPerformance),
        ("testResamplingCosinePerformance", testResamplingCosinePerformance),
        ("testResamplingCubicAntialiasPerformance", testResamplingCubicAntialiasPerformance),
        ("testResamplingCubicPerformance", testResamplingCubicPerformance),
        ("testResamplingHermiteAntialiasPerformance", testResamplingHermiteAntialiasPerformance),
        ("testResamplingHermitePerformance", testResamplingHermitePerformance),
        ("testResamplingLanczosAntialiasPerformance", testResamplingLanczosAntialiasPerformance),
        ("testResamplingLanczosPerformance", testResamplingLanczosPerformance),
        ("testResamplingLinearAntialiasPerformance", testResamplingLinearAntialiasPerformance),
        ("testResamplingLinearPerformance", testResamplingLinearPerformance),
        ("testResamplingMitchellAntialiasPerformance", testResamplingMitchellAntialiasPerformance),
        ("testResamplingMitchellPerformance", testResamplingMitchellPerformance),
        ("testResamplingNoneAntialiasPerformance", testResamplingNoneAntialiasPerformance),
        ("testResamplingNonePerformance", testResamplingNonePerformance),
        ("testStencilTextureConvolutionA", testStencilTextureConvolutionA),
        ("testStencilTextureConvolutionB", testStencilTextureConvolutionB),
        ("testStencilTextureConvolutionC", testStencilTextureConvolutionC),
    ]
}

extension LayoutTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayoutTest = [
        ("testColorComponentsLayout", testColorComponentsLayout),
        ("testColorModelLayout", testColorModelLayout),
        ("testComplexLayout", testComplexLayout),
        ("testFloat32ColorPixelLayout", testFloat32ColorPixelLayout),
        ("testFloat64ColorPixelLayout", testFloat64ColorPixelLayout),
        ("testPointLayout", testPointLayout),
        ("testVectorLayout", testVectorLayout),
    ]
}

extension MappedBufferTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MappedBufferTest = [
        ("testMappedBufferAlloc", testMappedBufferAlloc),
        ("testMappedBufferAppend", testMappedBufferAppend),
        ("testMappedBufferAppend2", testMappedBufferAppend2),
        ("testMappedBufferAppend3", testMappedBufferAppend3),
        ("testMappedBufferReplaceSubrange", testMappedBufferReplaceSubrange),
        ("testMappedBufferReplaceSubrange2", testMappedBufferReplaceSubrange2),
        ("testMappedBufferReplaceSubrange3", testMappedBufferReplaceSubrange3),
    ]
}

extension PolynomialTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PolynomialTest = [
        ("testPolynomialDivPerformance", testPolynomialDivPerformance),
        ("testPolynomialModPerformance", testPolynomialModPerformance),
        ("testPolynomialMulPerformance", testPolynomialMulPerformance),
        ("testPolynomialPowPerformance", testPolynomialPowPerformance),
    ]
}

extension ShapeRegionTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShapeRegionTest = [
        ("testShapeRegionEvenOdd", testShapeRegionEvenOdd),
        ("testShapeRegionIntersection", testShapeRegionIntersection),
        ("testShapeRegionNonZero", testShapeRegionNonZero),
        ("testShapeRegionSubtracting", testShapeRegionSubtracting),
        ("testShapeRegionSymmetricDifference", testShapeRegionSymmetricDifference),
        ("testShapeRegionUnion", testShapeRegionUnion),
    ]
}

extension XMLTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLTest = [
        ("testXMLA", testXMLA),
    ]
}

extension ZlibTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ZlibTest = [
        ("testDeflatePerformance", testDeflatePerformance),
        ("testGzip", testGzip),
        ("testInflatePerformance", testInflatePerformance),
        ("testZlib", testZlib),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArithmeticTest.__allTests__ArithmeticTest),
        testCase(BrotliTest.__allTests__BrotliTest),
        testCase(CollectionTest.__allTests__CollectionTest),
        testCase(ColorSpaceTest.__allTests__ColorSpaceTest),
        testCase(FontTest.__allTests__FontTest),
        testCase(FourierTest.__allTests__FourierTest),
        testCase(ImageCodecTest.__allTests__ImageCodecTest),
        testCase(ImageTest.__allTests__ImageTest),
        testCase(LayoutTest.__allTests__LayoutTest),
        testCase(MappedBufferTest.__allTests__MappedBufferTest),
        testCase(PolynomialTest.__allTests__PolynomialTest),
        testCase(ShapeRegionTest.__allTests__ShapeRegionTest),
        testCase(XMLTest.__allTests__XMLTest),
        testCase(ZlibTest.__allTests__ZlibTest),
    ]
}
#endif
