#!/bin/bash
#
#  The MIT License
#  Copyright (c) 2015 - 2020 Susan Cheng. All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#

set -e

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${PROJECT_DIR}
git submodule update --recursive

mkdir -p ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo

cd ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo
cmake -G Ninja ${PROJECT_DIR}/dependencies/libjpeg-turbo

rm -r ${PROJECT_DIR}/Sources/libjpeg/src || true
mkdir -p ${PROJECT_DIR}/Sources/libjpeg/src

SOURCES="$( ninja -t graph jpeg | grep -oE '"[^"]*\.c"' | tr -d '"' )"

for SOURCE in ${SOURCES}; do
  cp ${SOURCE} ${PROJECT_DIR}/Sources/libjpeg/src
done


rm -r ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg || true
mkdir -p ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg

cp ${PROJECT_DIR}/dependencies/libjpeg-turbo/jpeglib.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/dependencies/libjpeg-turbo/jmorecfg.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo/jconfig.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo/jconfigint.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
