#!/bin/bash
set -e

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd ${PROJECT_DIR}
git submodule update --recursive


# brotli

mkdir -p ${PROJECT_DIR}/.build/dependencies/brotli

cd ${PROJECT_DIR}/.build/dependencies/brotli
cmake -G Ninja ${PROJECT_DIR}/dependencies/brotli

rm -r ${PROJECT_DIR}/Sources/brotli/include/brotli || true
mkdir -p ${PROJECT_DIR}/Sources/brotli/include/brotli

cp ${PROJECT_DIR}/dependencies/brotli/c/include/brotli/* ${PROJECT_DIR}/Sources/brotli/include/brotli

rm -r ${PROJECT_DIR}/Sources/brotli/src || true
mkdir -p ${PROJECT_DIR}/Sources/brotli/src

SOURCES="$( ninja -t graph brotli | grep -oE '"[^"]*\.c"' | tr -d '"' )"

for SOURCE in ${SOURCES}; do
  cp ${SOURCE} ${PROJECT_DIR}/Sources/brotli/src
done


# libwebp

mkdir -p ${PROJECT_DIR}/.build/dependencies/libwebp

cd ${PROJECT_DIR}/.build/dependencies/libwebp
cmake -G Ninja ${PROJECT_DIR}/dependencies/libwebp

rm -r ${PROJECT_DIR}/Sources/libwebp/include/webp || true
mkdir -p ${PROJECT_DIR}/Sources/libwebp/include/webp

cp ${PROJECT_DIR}/dependencies/libwebp/src/webp/* ${PROJECT_DIR}/Sources/libwebp/include/webp

rm -r ${PROJECT_DIR}/Sources/libwebp/src || true
mkdir -p ${PROJECT_DIR}/Sources/libwebp/src

SOURCES="$( ninja -t graph webp | grep -oE '"[^"]*\.c"' | tr -d '"' )"

for SOURCE in ${SOURCES}; do
  cp ${SOURCE} ${PROJECT_DIR}/Sources/libwebp/src
done


# libjpeg-turbo

mkdir -p ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo

cd ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo
cmake -G Ninja ${PROJECT_DIR}/dependencies/libjpeg-turbo

rm -r ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg || true
mkdir -p ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg

cp ${PROJECT_DIR}/dependencies/libjpeg-turbo/jpeglib.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/dependencies/libjpeg-turbo/jmorecfg.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo/jconfig.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg
cp ${PROJECT_DIR}/.build/dependencies/libjpeg-turbo/jconfigint.h ${PROJECT_DIR}/Sources/libjpeg/include/libjpeg

rm -r ${PROJECT_DIR}/Sources/libjpeg/src || true
mkdir -p ${PROJECT_DIR}/Sources/libjpeg/src

SOURCES="$( ninja -t graph jpeg-static | grep -oE '"[^"]*\.c"' | tr -d '"' )"

for SOURCE in ${SOURCES}; do
  cp ${SOURCE} ${PROJECT_DIR}/Sources/libjpeg/src
done

