#!/bin/bash
set -e

if [ -e ./Package-Builder/build-package.sh ]; then
  git clone https://github.com/SusanDoggie/Package-Builder.git
fi

if [ -n "${DOCKER_IMAGE}" ]; then
  docker pull ${DOCKER_IMAGE}
  docker run --env SWIFT_SNAPSHOT -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} ${DOCKER_IMAGE} /bin/bash -c "cd $TRAVIS_BUILD_DIR && ./.travis/build-package"
  exit $?
fi

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  mv ./.travis/before-install-swift ./.before-install-swift
fi

while true; do echo "..."; sleep 60; done &
./Package-Builder/build-package.sh
kill %1
