//: Playground - noun: a place where people can play

import Cocoa
import Doggie

Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
Double.random(includeOne: true)
