name: Builder
on: [push, pull_request]
jobs:
  platform:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: [macosx, iphonesimulator, appletvsimulator]
        include:
          - sdk: macosx
            name: macOS
            destination: 'platform=macOS'
          - sdk: iphonesimulator
            name: iOS
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - sdk: appletvsimulator
            name: tvOS
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    env:
      DESTINATION: ${{ matrix.destination }}
      XCODEBUILD_CONFIG: "-configuration Release -sdk ${{ matrix.sdk }}"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: |
        SCHEMES=$(xcodebuild -list | grep --after-context=-1 '^\s*Schemes:' | tail -n +2 | xargs)
        for SCHEME in ${SCHEMES}; do
          echo "Building scheme ${SCHEME}"
          xcodebuild ${XCODEBUILD_CONFIG} -scheme ${SCHEME} | xcpretty -f `xcpretty-travis-formatter`
        done
    - name: Run tests
      run: |
        SCHEMES=$(xcodebuild -list | grep --after-context=-1 '^\s*Schemes:' | tail -n +2 | xargs)
        for SCHEME in ${SCHEMES}; do
          echo "Testing scheme ${SCHEME}"
          xcodebuild ${XCODEBUILD_CONFIG} -scheme ${SCHEME} build-for-testing -skipUnavailableActions | xcpretty -f `xcpretty-travis-formatter`
          xcodebuild ${XCODEBUILD_CONFIG} -scheme ${SCHEME} -destination "${DESTINATION}" test-without-building -skipUnavailableActions | xcpretty -f `xcpretty-travis-formatter`
        done
  macos:
    name: macOS(SwiftPM)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
  ubuntu:
    name: ${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [xenial, bionic]
    steps:
    - run: apt-get -q update && apt-get -y -q install libz-dev
    - run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig ttf-mscorefonts-installer
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
