name: Builder
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        name: [macOS, macCatalyst, iOS, tvOS, macOS(SwiftPM)]
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
            enable_codecov: true
          - name: macCatalyst
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS,variant=Mac Catalyst'
          - name: iOS
            use_xcodebuild: true
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            use_xcodebuild: true
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  ubuntu_swift_latest:
    name: latest-${{ matrix.image }}
    container:
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [xenial, bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install ICC profiles
      run: apt-get install -y icc-profiles
    - name: Install fonts
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig fonts-noto ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  linux_swift_latest:
    name: latest-${{ matrix.image }}
    container:
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [centos8, amazonlinux2]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: yum update -y
    - name: Install fonts
      run: yum install -y fontconfig google-noto-*
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  ubuntu_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-xenial, nightly-bionic, nightly-focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install ICC profiles
      run: apt-get install -y icc-profiles
    - name: Install fonts
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig fonts-noto ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  linux_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-centos7, nightly-centos8, nightly-amazonlinux2]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: yum update -y
    - name: Install fonts
      run: yum install -y fontconfig google-noto-*
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
