name: Builder
on: [push, pull_request]
jobs:
  darwin:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: [macosx, iphonesimulator, appletvsimulator]
        include:
          - name: macOS
            enable_codecov: true
            sdk: macosx
            destination: 'platform=macOS'
          - name: iOS
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    env:
      USE_XCOEBUILD: true
      SDK: ${{ matrix.sdk }}
      DESTINATION: ${{ matrix.destination }}
      ENABLE_CODECOV: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  macos:
    name: macOS(SwiftPM)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
  ubuntu:
    name: ${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [xenial, bionic]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: apt-get -q update && apt-get -y -q install libz-dev
    - name: Install fonts
      run: |		
        export DEBIAN_FRONTEND=noninteractive		
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections		
        apt-get install -y fontconfig ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
