name: Builder
on: [push, pull_request]
jobs:
  darwin:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        sdk: [macosx, iphonesimulator, appletvsimulator]
        include:
          - name: macOS
            enable_codecov: true
            sdk: macosx
            destination: 'platform=macOS'
          - name: iOS
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
    env:
      use_xcodebuild: true
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  macos:
    name: macOS(SwiftPM)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
  ubuntu_swift_latest:
    name: latest-${{ matrix.image }}
    container:
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [xenial, bionic]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      run: apt-get update
    - name: Install ICC profiles
      run: apt-get install -y icc-profiles
    - name: Install fonts
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig fonts-noto ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
  swift_5_1:
    name: ${{ matrix.image }}
    container:
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [5.1-xenial, 5.1-bionic]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
  ubuntu_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-xenial, nightly-bionic, nightly-focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
  linux_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-centos8, nightly-amazonlinux2]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install dependencies
      run: yum update && yum install -y zlib-devel
    - name: Build
      uses: SusanDoggie/swift-action@master
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@master
      with:
        action: test
