name: Builder
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        name: [macOS, macCatalyst, iOS, tvOS, macOS(SwiftPM)]
        xcode_version: ['14.0']
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
            enable_codecov: true
          - name: macCatalyst
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS,variant=Mac Catalyst'
          - name: iOS
            use_xcodebuild: true
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 11'
          - name: tvOS
            use_xcodebuild: true
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV 4K'
          - name: macOS(SwiftPM)
            use_xcodebuild: false
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      schemes: Doggie-Package
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode_version }}
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v2
      if: ${{ matrix.enable_codecov }}
  ubuntu_swift:
    name: ${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swift:${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.7]
        distro: [bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      run: apt-get update
    - name: Install ICC profiles
      run: apt-get install -y icc-profiles
    - name: Install fonts
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig fonts-noto ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  ubuntu_swift_nightly:
    name: nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swiftlang/swift:nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        swift_version: [main, 5.7]
        distro: [bionic, focal, jammy]
        exclude:
          - swift_version: 5.7
            distro: jammy
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      run: apt-get update
    - name: Install ICC profiles
      run: apt-get install -y icc-profiles
    - name: Install fonts
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
        apt-get install -y fontconfig fonts-noto ttf-mscorefonts-installer
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
