name: Swift

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
  xenial:
    container: 
      image: docker://swift:xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
  bionic:
    container: 
      image: docker://swift:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: swift build -c release
    - name: Run tests
      run: swift test -c release
